# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:



- task: AmazonWebServices.aws-vsts-tools.AWSShellScript.AWSShellScript@1
  displayName: 'AWS Shell Script'
  inputs:
    awsCredentials: 'AWS_ECR_TEST'
    regionName: 'us-east-1'
    scriptType: inline
    inlineScript: |
      echo 'Using identity'
      aws sts get-caller-identity

      ## ECR Login
      export HELM_EXPERIMENTAL_OCI=1

      echo "##[section]kubectl get all -n $(K8sNamespace)"
      kubectl get all -n A