name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        ls -l
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run tests
    #   run: |
    #     pip install pytest
    #     pytest test_main.py -vv

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: app-sumatoria
        IMAGE_TAG: release-${{ github.run_id }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Kubernetes manifest with new image tag
      run: |
        sed -i "s/latest/${IMAGE_TAG}/g" manifest/deployment.yaml
        cat manifest/deployment.yaml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-2 --name cluster-eks

    - name: Apply Kubernetes manifest
      run: |
        kubectl apply -f manifest/deployment.yaml
        kubectl get all -A
